package hardcorefixes.reference;

import cpw.mods.fml.common.ModMetadata;

import java.util.Arrays;

public class Metadata
{
    public static ModMetadata init(ModMetadata metadata)
    {
        metadata.modId = Reference.ID;
        metadata.name = Reference.NAME;
        metadata.description = "Speed boost for HQM searching";
        metadata.url = "https://github.com/hilburn/HardcoreFixes";
        metadata.version = Reference.VERSION_FULL;
        metadata.authorList = Arrays.asList("hilburn");
        metadata.credits = "";
        metadata.autogenerated = false;
        return metadata;
    }
}
